const products = [
    {
      id: 1,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/t-shirt_black_logo_front_1_ezpnfr",
      name: "Black T-Shirt",
      price: 19.99,
      category: "Tshirts",
      imageHeight: 200,
    },
    {
      id: 2,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/t-shirt_black_logo_front_1_ezpnfr",
      name: "Black T-Shirt",
      price: 19.99,
      category: "Tshirts",
      imageHeight: 200,
    },
    {
      id: 3,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/t-shirt_black_logo_front_1_ezpnfr",
      name: "Black T-Shirt",
      price: 19.99,
      category: "Tshirts",
      imageHeight: 200,
    },
    {
      id: 4,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/OIP_meeqih",
      name: "Black Hoodie",
      price: 24.99,
      category: "Hoodies",
      imageHeight: 200,
    },
    {
      id: 5,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/OIP_meeqih",
      name: "Black Hoodie",
      price: 24.99,
      category: "Hoodies",
      imageHeight: 200,
    },
    {
      id: 6,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/OIP_meeqih",
      name: "Black Hoodie",
      price: 24.99,
      category: "Hoodies",
      imageHeight: 200,
    },
    {
      id: 7,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/1391213369_fvjiz0",
      name: "Dual-Tone Runners",
      price: 12.99,
      category: "Shoes",
      imageHeight: 200,
    },
    {
      id: 8,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/1391213369_fvjiz0",
      name: "Dual-Tone Runners",
      price: 12.99,
      category: "Shoes",
      imageHeight: 200,
    },
    {
      id: 9,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/1391213369_fvjiz0",
      name: "Dual-Tone Runners",
      price: 12.99,
      category: "Shoes",
      imageHeight: 200,
    },
    {
      id: 10,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/bf051_g2_lbwnnq",
      name: "Travel Messenger Bag",
      price: 29.99,
      category: "Bags",
      imageHeight: 200,
    },
    {
      id: 11,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/bf051_g2_lbwnnq",
      name: "Travel Messenger Bag",
      price: 29.99,
      category: "Bags",
      imageHeight: 200,
    },
    {
      id: 12,
      imageUrl: "https://res.cloudinary.com/dr1pmtefx/image/upload/f_auto,q_auto/bf051_g2_lbwnnq",
      name: "Travel Messenger Bag",
      price: 29.99,
      category: "Bags",
      imageHeight: 200,
    },
  ];

export default products